# version: "3.3"
# services:
#  db:
#     container_name: 'database-postgres'
#     image: postgres:14-alpine
#     volumes:
#       - ./data/db:/var/lib/postgresql/data
#     environment:
#       - POSTGRES_DB=postgres
#       - POSTGRES_USER=postgres
#       - POSTGRES_PASSWORD=postgres
#  web:
#     container_name: 'mysite-web'
#     build: .
#     command: /bin/sh -c -- "while true; do sleep 300; done;"
#     volumes:
#       - .:/mysite
#     ports:
#       - "8000:8000"
#     environment:
#       - POSTGRES_NAME=postgres
#       - POSTGRES_USER=postgres
#       - POSTGRES_PASSWORD=postgres
version: "3.3"
services:
  db:
    container_name: 'mydb'
    image: postgres:14-alpine
    volumes:
      - ./data/db:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
  web:
    container_name: 'mysite-web'
    build: .
    command: /bin/sh -c -- "while true; do sleep 300; done;"
    volumes:
      - .:/mysite
    ports:
      - "8000:8000"
    environment:
      - POSTGRES_NAME=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_HOST=db
    depends_on:
      - db